[package]
name = "rproxychainsd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
toml = "0.5.10"
serde = { version = "1.0.150", features = ["derive"] }
thiserror = "1.0.37"
anyhow = "1.0.66"
futures = "0.3.25"
rand = "0.8.5"
